name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:       
      - name: Deploy to gh-pages
        run: |
          # Configure git
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Checkout gh-pages branch
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          
          # Clean the gh-pages branch (Optional, if needed)
          rm -rf *
          
          # Copy the Build folder content to gh-pages
          cp -r ../Build/* .

          # Commit and push the changes to gh-pages branch
          git add .
          git commit -m 'Deploy build to gh-pages'
          git push origin gh-pages

      - name: Push changes to master (if necessary)
        run: |
          git checkout master
          git add .
          git commit -m 'Update master branch'
          git push origin master
