name: Build and run

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ libcurl4-openssl-dev nlohmann-json3-dev

      - name: Build HaletasWeb site generator
        run: |
          mkdir -p build
          g++ -std=c++17 -o build/site Src/Main.cpp -lcurl

      - name: Run HaletasWeb generator
        run: |
          ./build/site

      - name: Deploy 'out/' to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
