name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # At 03:00 PM (UTC)
    - cron: "0 15 * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ libcurl4-openssl-dev nlohmann-json3-dev

      - name: Build HaletasWeb site generator
        run: |
          mkdir -p build
          g++ -std=c++17 -o build/site Src/Main.cpp -lcurl

      - name: Run HaletasWeb generator
        run: |
          ./build/site

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: './out'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: run
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4