name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Only deploy when there are changes to the master branch

permissions:
  contents: write  # Allow writing to repository contents (this is needed for pushing to gh-pages)

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner for MSBuild

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git VCPKG  # Clone vcpkg into the VCPKG directory
        cd VCPKG
        .\bootstrap-vcpkg.bat  # Bootstraps vcpkg to create vcpkg.exe

    - name: Install dependencies with vcpkg
      run: |
        cd VCPKG
        .\vcpkg install nlohmann-json curl  # Install necessary libraries

    - name: Integrate vcpkg with MSBuild
      run: |
        cd VCPKG
        .\vcpkg integrate install  # Integrate vcpkg with MSBuild

    - name: Build the project using MSBuild
      run: |
        msbuild Website.sln /p:Configuration=Release /p:Platform=x64 /p:OutDir=./Build/

    - name: List build output
      run: |
        dir ./Build  # List the contents of the output directory to verify

    - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: './Build'

    - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: run
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4