name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

      - name: Clean the gh-pages branch (Optional)
        run: |
          rm -rf *  # This deletes everything in the gh-pages branch

      - name: Copy Build folder to gh-pages
        run: |
          cp -r ../Build/* .  # Copy the Build folder contents to gh-pages branch

      - name: Commit and push to gh-pages
        run: |
          git add .
          git commit -m 'Deploy build to gh-pages'
          git push origin gh-pages

      - name: Push changes to master (if necessary)
        run: |
          git checkout master
          git add .
          git commit -m 'Update master branch'
          git push origin
