name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Only deploy when there are changes to the master branch

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner for MSBuild

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build the project using MSBuild
      run: |
        msbuild Website.sln /p:Configuration=Release /p:Platform="x64"
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Build  # Directory where your built files are located
        publish_branch: gh-pages  # Target branch for GitHub Pages
